# a mybinder.org-ready environment for demoing jupyterlab_webrtc_docprovider
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-webrtc-docprovider-demo
#
name: jupyterlab-webrtc-docprovider-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.9,<3.10.0a0
  - jupyterlab >=3.1,<4.0.0a0
  - retrolab
  # labextension build dependencies
  - nodejs >=16,<17
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
