name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install Python dependencies
      run: |
        python -m pip install -U jupyterlab~=3.1 check-manifest build
        pip freeze

    - name: Install Node dependencies
      run: jlpm

    - name: Lint
      run: jlpm lint:check

    - name: Build JS
      run: |
        set -eux
        jlpm build:prod
        mkdir dist
        cd dist && npm pack ..

    - name: Build Python
      run: |
        set -eux
        python -m build --sdist
    
    - name: Hash distributions
      run: |
        set -eux
        cd dist
        sha256sum * | tee SHA256SUMS

    - uses: actions/upload-artifact@v3
      with:
        name: jupyterlab-webrtc-docprovider dist ${{ github.run_number }}
        path: dist

  test_isolated:
    needs: build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'

    - uses: actions/download-artifact@v3
      with:
        name: jupyterlab-webrtc-docprovider dist ${{ github.run_number }}
        path: dist

    - name: Prep (unix)
      if: matrix.os != 'windows'
      run: |
        set -eux
        sudo rm -rf $(which node)
        sudo rm -rf $(which node)

    - name: Install and Test
      run: |
        cd dist
        pip install --find-links=. jupyterlab-webrtc-docprovider --no-deps
        pip install "jupyterlab>=3.1,<4"

    - name: Check installed packages
      run: |
        pip freeze
        pip check

    - name: List Lab Extensions
      run: |
        jupyter labextension list
        jupyter labextension list > labextensions.txt 2>&1
        python -m jupyterlab.browser_check --no-chrome-test

    - name: Check Lab Extensions
      if: matrix.os != 'windows'
      run: grep -E "@jupyterlite/webrtc-docprovider.*OK" labextensions.txt
